Repository Zohaib-Kenny-Zakaria-Wilson/fitcast, pull requests merged in 2024-06, with the labels that each got.

#1 Create pages
  fitcast/src/App.js
  fitcast/src/pages/Homepage.jsx
  fitcast/src/pages/Wardrobe.jsx
Labels: enhancement

#2 Fix: Fixed the structure of the repo due to an extra unnecessary fitcast folder
  .gitignore
  README.md
  fitcast/README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Homepage.jsx
  src/pages/Wardrobe.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement

#3 Installed Tailwind
  package-lock.json
  package.json
  src/App.js
  src/index.css
  tailwind.config.js
Labels: enhancement

#4 Temporary layout for the homepage
  src/App.js
  src/pages/Homepage.jsx
Labels: enhancement

#5 feat: Add Button component to App.js
  src/App.js
  src/components/Button.jsx
  tailwind.config.js
Labels: enhancement

#7 Create backend
  csharp_backend/Program.java
  public/index.html
Labels: enhancement

#10 "Add main section of display"
  public/assets/fitcast.svg
  public/index.html
  src/components/Button.jsx
  src/components/Sidebar.jsx
  src/components/WeatherKeyInfo.jsx
  tailwind.config.js
Labels: enhancement

#12 Weather api setup
  pom.xml
  src/java/Program.java
  target/maven-archiver/pom.properties
  target/my-java-project-1.0-SNAPSHOT.jar
Labels: enhancement

#15 Basic interaction with weather api
  .gitignore
  src/java/Program.class
  src/java/Program.java
Labels: enhancement

#14 chore: Increase font size for city name in WeatherDisplay component
  src/components/WeatherDisplay.jsx
Labels: Improvement

#21 FIT-1: Added Media Queries
  src/App.js
  src/components/Logo.jsx
  src/components/WeatherDisplay.jsx
  src/components/WeatherKeyInfo.jsx
Labels: Improvement

#32 FIT-11: Create Clothing Item Component Expanded
  public/assets/white-shirt.png
  src/App.js
  src/components/ClothingDisplay.jsx
  src/components/ClothingDisplayComponents/ClothingMiniDisplay.jsx
  src/components/ClothingDisplayComponents/ClothingTag.jsx
  src/components/ClothingDisplayComponents/ClothingTagContainer.jsx
Labels: feature

#65 FIT-35: File-Upload-and-Color-change
  package-lock.json
  package.json
  src/components/ItemComponents/ItemExpanded.jsx
  src/components/ItemComponents/ItemMini.jsx
  src/context/useAppContext.jsx
Labels: feature

#88 FIT-24-Clean-up-code
  src/App.js
  src/components/ItemComponents/ItemExpanded.jsx
  src/components/PageComponents/TodayOutfitContainer.jsx
  src/components/PageComponents/Wthr.jsx
  src/components/PageComponents/navBar.jsx
  src/components/TodayOutfitContainer.jsx
  src/components/Wardrobe.jsx
  src/java/Program.java
  src/pages/DailyOutfitPage.jsx
  src/pages/Homepage.jsx
  src/pages/Wardrobe.jsx
  src/utils/getWeatherIcon.js
Labels: Improvement
